set_property SRC_FILE_INFO {cfile:/home/xarez/Documents/CR/ClockDivider/ClockDivider.srcs/constrs_1/imports/tutorial/Nexys4_Master.xdc rfile:../../../ClockDivider.srcs/constrs_1/imports/tutorial/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports {led[0]}]
