# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/fabio/Code/mips/mips/mips.cache/wt [current_project]
set_property parent.project_path /home/fabio/Code/mips/mips/mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/fabio/Code/mips/mips/mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/ALU.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/ALUControlUnit.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/ControlUnit.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/PCupdate.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/Mux2to1.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/RAM.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/RegisterN.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/InstrSplitter.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/SignExtend.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/LeftShifter2.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/DP_Memory.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/RegFile.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/Mux4to1.vhd
  /home/fabio/Code/mips/mips/mips.srcs/sources_1/new/CPU.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fabio/Code/mips/mips/mips.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/fabio/Code/mips/mips/mips.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]


synth_design -top CPU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
